# Generated by Django 3.2.6 on 2021-09-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('code', models.BigIntegerField()),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('stores', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosen_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choosen_product', to='foods.products')),
                ('substitue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='foods.products')),
            ],
        ),
    ]
