# Generated by Django 3.2.6 on 2021-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
