# Generated by Django 3.2.6 on 2021-09-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20210906_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrition_grade',
            field=models.CharField(max_length=255),
        ),
    ]
