# Generated by Django 3.2.6 on 2021-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210906_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
